services:
  app: 
    image: ayomeer/cv-devcontainer-image:latest
    container_name: devcontainer
    network_mode: host  # needed, so host.docker.internal points to actual host IP
                        # and not Docker subnet
    volumes:
      - .:/app          # mount project directory
    
    environment:
     - DISPLAY=host.docker.internal:0.0 # set display environment to local host IP
     - MPLBACKEND=TkAgg                 # set matplotlib backend to graphics capable one
    stdin_open: true
    tty: true
