services:
  app: 
    image: ayomeer/cv-devcontainer-image:noprjfiles
    container_name: devcontainer
    command: sh
    network_mode: host  # works despite documentation saying it only works for linux host
                        # --> needed, so host.docker.internal points to actual host IP
                        #     and not Docker subnet
    volumes:
      - ./_img:/app/_img
      - ./python:/app/python
      - ./cpp:/app/cpp
    environment:
      - DISPLAY=host.docker.internal:0.0 # set display environment to host IP
      - MPLBACKEND=TkAgg
      - PYTHONBREAKPOINT=ipdb.set_trace  # use ipdb for breakpoint()-function
    stdin_open: true
    tty: true