services:
  app: 
    image: ayomeer/cv-devcontainer-image:latest
    container_name: devcontainer
    privileged: true
    command: sh
    network_mode: host  # works despite documentation saying it only works for linux host
                        # --> needed, so host.docker.internal points to actual host IP
                        #     and not Docker subnet
    volumes:
      - .:/app
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - $HOME/.Xauthority:/root/.Xauthority:rw 
    
    environment:
      - DISPLAY=$DISPLAY

    stdin_open: true
    tty: true
