services:
  app: 
    image: ayomeer/cv-devcontainer-image:cvcuda
    container_name: cv-devcontainer
    command: sh
    network_mode: host  
                       
    volumes:
      - .:/app
          
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] # equivalent of '--gpus=all' in docker run command

    environment:
      - DISPLAY=host.docker.internal:0.0 # [WIN] set display environment to host IP
      - MPLBACKEND=TkAgg                 # [WIN] set matplotlib backend to X11 compatible one

    stdin_open: true
    tty: true