services:
  app: 
    image: ayomeer/cv-devcontainer-image:cvcuda
    container_name: devcontainer
    command: sh
    network_mode: host  # works despite documentation saying it only works for linux host
                        # --> needed, so host.docker.internal points to actual host IP
                        #     and not Docker subnet for X11 GUI
    volumes:
      - .:/app
          
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] # equivalent of '--gpus=all' in docker run command

   
    environment:
      - DISPLAY=host.docker.internal:0.0 # [WIN] set display environment to host IP
      - MPLBACKEND=TkAgg                 # [WIN] set matplotlib backend to X11 compatible one
      # - PYTHONBREAKPOINT=ipdb.set_trace  # use ipdb for breakpoint()-function
    stdin_open: true
    tty: true
