# based on: https://docs.docker.com/build/ci/github-actions/test-before-push/

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    # all branches
env:
  TEST_TAG: ayomeer/cv-devcontainer-image:ci_build
  LATEST_TAG: ayomeer/cv-devcontainer-image:latest
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true # make available locally for testing
          tags: ${{ env.TEST_TAG }}
      
#      - name: Test
#        run: |
#          docker run --rm ${{ env.TEST_TAG }}
      
