name: DevContainer CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    # all branches
  workflow_dispatch:
    # manual dispatch from github actions tab 
    # (will push image to Docker Hub if tests passed)
env:
  TAG: ayomeer/cv-devcontainer-image:main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false # don't push to repo until unit tests passed
          load: true  # make available locally for testing
          tags: build_test # tag given in .github/docker-compose.ci  
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Unit Test
        run: docker-compose -f .github/docker-compose.ci.yml run app python3 ./python/unitTests.py
        # failed test return will propagate through docker run command and fail CI
        
        
      - name: Build Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push:  ${{ github.event_name != 'pull_request' }} # don't push to Docker Hub if triggered by
          tags: ${{ env.TAG }} # push as main tag           # pull request activity
          cache-from: type=gha
          cache-to: type=gha,mode=max
